import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

// Node.js built-ins with 'node:' prefix for packages that use modern syntax
const nodeBuiltinsWithPrefix = builtins.map(mod => `node:${mod}`);

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    // Node.js built-ins (both with and without node: prefix)
    ...builtins,
    ...nodeBuiltinsWithPrefix,
  ],
  loader: {
    ".node": "file",
  },
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
  mainFields: ["browser", "module", "main"]
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
